import type { WhiteboardTemplate, ExcalidrawElement } from '../types';

// Helper to generate random IDs
function generateId(): string {
  return Math.random().toString(36).substring(2, 15);
}

function generateSeed(): number {
  return Math.floor(Math.random() * 2147483647);
}

// Base element properties
function createBaseProps(): Partial<ExcalidrawElement> {
  return {
    angle: 0,
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: generateSeed(),
    version: 1,
    versionNonce: generateSeed(),
    isDeleted: false,
    boundElements: null,
    updated: Date.now(),
    link: null,
    locked: false,
  };
}

// C4 Context Diagram Template
export const c4ContextTemplate: WhiteboardTemplate = {
  id: 'c4-context',
  name: 'C4 Context Diagram',
  description: 'Diagrama de contexto do sistema mostrando usuários e sistemas externos',
  category: 'architecture',
  elements: [
    // Person (User)
    {
      id: generateId(),
      type: 'ellipse',
      x: 100,
      y: 50,
      width: 80,
      height: 80,
      strokeColor: '#1e1e1e',
      backgroundColor: '#ffc9c9',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 105,
      y: 140,
      width: 70,
      height: 25,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Usuário',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      baseline: 18,
      containerId: null,
      originalText: 'Usuário',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Main System
    {
      id: generateId(),
      type: 'rectangle',
      x: 300,
      y: 50,
      width: 200,
      height: 120,
      strokeColor: '#1e1e1e',
      backgroundColor: '#a5d8ff',
      roundness: { type: 3, value: 10 },
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 340,
      y: 95,
      width: 120,
      height: 30,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Sistema Principal',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      containerId: null,
      originalText: 'Sistema Principal',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // External System
    {
      id: generateId(),
      type: 'rectangle',
      x: 550,
      y: 50,
      width: 150,
      height: 100,
      strokeColor: '#868e96',
      backgroundColor: '#e9ecef',
      roundness: { type: 3, value: 10 },
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 565,
      y: 85,
      width: 120,
      height: 30,
      strokeColor: '#868e96',
      backgroundColor: 'transparent',
      text: 'Sistema Externo',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Sistema Externo',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
  ],
};

// ERD Template
export const erdTemplate: WhiteboardTemplate = {
  id: 'erd',
  name: 'Entity Relationship Diagram',
  description: 'Diagrama de entidades e relacionamentos para modelagem de dados',
  category: 'architecture',
  elements: [
    // Entity 1
    {
      id: generateId(),
      type: 'rectangle',
      x: 100,
      y: 100,
      width: 180,
      height: 120,
      strokeColor: '#1e1e1e',
      backgroundColor: '#d0bfff',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 150,
      y: 110,
      width: 80,
      height: 25,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Usuário',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      baseline: 18,
      containerId: null,
      originalText: 'Usuário',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'line',
      x: 100,
      y: 140,
      width: 180,
      height: 0,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      points: [[0, 0], [180, 0]],
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 110,
      y: 150,
      width: 160,
      height: 60,
      strokeColor: '#495057',
      backgroundColor: 'transparent',
      text: 'id: UUID\nnome: String\nemail: String',
      fontSize: 12,
      fontFamily: 3,
      textAlign: 'left',
      verticalAlign: 'top',
      baseline: 14,
      containerId: null,
      originalText: 'id: UUID\nnome: String\nemail: String',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Entity 2
    {
      id: generateId(),
      type: 'rectangle',
      x: 400,
      y: 100,
      width: 180,
      height: 120,
      strokeColor: '#1e1e1e',
      backgroundColor: '#b2f2bb',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 455,
      y: 110,
      width: 70,
      height: 25,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Projeto',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      baseline: 18,
      containerId: null,
      originalText: 'Projeto',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'line',
      x: 400,
      y: 140,
      width: 180,
      height: 0,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      points: [[0, 0], [180, 0]],
      ...createBaseProps(),
    } as ExcalidrawElement,
  ],
};

// Sprint Board Template
export const sprintBoardTemplate: WhiteboardTemplate = {
  id: 'sprint-board',
  name: 'Sprint Board',
  description: 'Quadro Kanban para gerenciamento de sprints',
  category: 'planning',
  elements: [
    // To Do Column
    {
      id: generateId(),
      type: 'rectangle',
      x: 50,
      y: 50,
      width: 200,
      height: 400,
      strokeColor: '#868e96',
      backgroundColor: '#fff9db',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 115,
      y: 60,
      width: 70,
      height: 30,
      strokeColor: '#e67700',
      backgroundColor: 'transparent',
      text: 'To Do',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      baseline: 22,
      containerId: null,
      originalText: 'To Do',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // In Progress Column
    {
      id: generateId(),
      type: 'rectangle',
      x: 270,
      y: 50,
      width: 200,
      height: 400,
      strokeColor: '#868e96',
      backgroundColor: '#d0ebff',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 310,
      y: 60,
      width: 120,
      height: 30,
      strokeColor: '#1971c2',
      backgroundColor: 'transparent',
      text: 'In Progress',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      baseline: 22,
      containerId: null,
      originalText: 'In Progress',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Done Column
    {
      id: generateId(),
      type: 'rectangle',
      x: 490,
      y: 50,
      width: 200,
      height: 400,
      strokeColor: '#868e96',
      backgroundColor: '#d3f9d8',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 560,
      y: 60,
      width: 60,
      height: 30,
      strokeColor: '#2f9e44',
      backgroundColor: 'transparent',
      text: 'Done',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      baseline: 22,
      containerId: null,
      originalText: 'Done',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
  ],
};

// Flowchart Template
export const flowchartTemplate: WhiteboardTemplate = {
  id: 'flowchart',
  name: 'Flowchart',
  description: 'Fluxograma básico para processos e decisões',
  category: 'diagram',
  elements: [
    // Start (Rounded rectangle)
    {
      id: generateId(),
      type: 'rectangle',
      x: 200,
      y: 50,
      width: 120,
      height: 50,
      strokeColor: '#1e1e1e',
      backgroundColor: '#b2f2bb',
      roundness: { type: 3, value: 25 },
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 230,
      y: 65,
      width: 60,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Início',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      containerId: null,
      originalText: 'Início',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Process (Rectangle)
    {
      id: generateId(),
      type: 'rectangle',
      x: 200,
      y: 150,
      width: 120,
      height: 60,
      strokeColor: '#1e1e1e',
      backgroundColor: '#a5d8ff',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 215,
      y: 170,
      width: 90,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Processo',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      containerId: null,
      originalText: 'Processo',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Decision (Diamond)
    {
      id: generateId(),
      type: 'diamond',
      x: 200,
      y: 260,
      width: 120,
      height: 80,
      strokeColor: '#1e1e1e',
      backgroundColor: '#ffec99',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 218,
      y: 290,
      width: 85,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Decisão?',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Decisão?',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // End (Rounded rectangle)
    {
      id: generateId(),
      type: 'rectangle',
      x: 200,
      y: 400,
      width: 120,
      height: 50,
      strokeColor: '#1e1e1e',
      backgroundColor: '#ffc9c9',
      roundness: { type: 3, value: 25 },
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 235,
      y: 415,
      width: 50,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Fim',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      containerId: null,
      originalText: 'Fim',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
  ],
};

// User Story Map Template
export const userStoryMapTemplate: WhiteboardTemplate = {
  id: 'user-story-map',
  name: 'User Story Map',
  description: 'Mapa de histórias de usuário para planejamento de produto',
  category: 'planning',
  elements: [
    // Activities Row
    {
      id: generateId(),
      type: 'rectangle',
      x: 50,
      y: 50,
      width: 600,
      height: 60,
      strokeColor: '#1971c2',
      backgroundColor: '#d0ebff',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 300,
      y: 70,
      width: 100,
      height: 25,
      strokeColor: '#1971c2',
      backgroundColor: 'transparent',
      text: 'Atividades',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      containerId: null,
      originalText: 'Atividades',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Tasks Row
    {
      id: generateId(),
      type: 'rectangle',
      x: 50,
      y: 130,
      width: 600,
      height: 50,
      strokeColor: '#5c940d',
      backgroundColor: '#d8f5a2',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 310,
      y: 145,
      width: 80,
      height: 25,
      strokeColor: '#5c940d',
      backgroundColor: 'transparent',
      text: 'Tarefas',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      containerId: null,
      originalText: 'Tarefas',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Release 1 Row
    {
      id: generateId(),
      type: 'rectangle',
      x: 50,
      y: 200,
      width: 600,
      height: 80,
      strokeColor: '#e67700',
      backgroundColor: '#fff3bf',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 290,
      y: 230,
      width: 120,
      height: 25,
      strokeColor: '#e67700',
      backgroundColor: 'transparent',
      text: 'Release 1 (MVP)',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Release 1 (MVP)',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Release 2 Row
    {
      id: generateId(),
      type: 'rectangle',
      x: 50,
      y: 300,
      width: 600,
      height: 80,
      strokeColor: '#868e96',
      backgroundColor: '#f1f3f5',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 305,
      y: 330,
      width: 90,
      height: 25,
      strokeColor: '#868e96',
      backgroundColor: 'transparent',
      text: 'Release 2',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Release 2',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
  ],
};

// Sequence Diagram Template
export const sequenceDiagramTemplate: WhiteboardTemplate = {
  id: 'sequence-diagram',
  name: 'Sequence Diagram',
  description: 'Diagrama de sequência para interações entre componentes',
  category: 'diagram',
  elements: [
    // Actor 1
    {
      id: generateId(),
      type: 'rectangle',
      x: 100,
      y: 50,
      width: 100,
      height: 40,
      strokeColor: '#1e1e1e',
      backgroundColor: '#a5d8ff',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 120,
      y: 60,
      width: 60,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Cliente',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Cliente',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'line',
      x: 150,
      y: 90,
      width: 0,
      height: 300,
      strokeColor: '#868e96',
      backgroundColor: 'transparent',
      strokeStyle: 'dashed',
      points: [[0, 0], [0, 300]],
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Actor 2
    {
      id: generateId(),
      type: 'rectangle',
      x: 300,
      y: 50,
      width: 100,
      height: 40,
      strokeColor: '#1e1e1e',
      backgroundColor: '#b2f2bb',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 320,
      y: 60,
      width: 60,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Servidor',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Servidor',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'line',
      x: 350,
      y: 90,
      width: 0,
      height: 300,
      strokeColor: '#868e96',
      backgroundColor: 'transparent',
      strokeStyle: 'dashed',
      points: [[0, 0], [0, 300]],
      ...createBaseProps(),
    } as ExcalidrawElement,
    // Actor 3
    {
      id: generateId(),
      type: 'rectangle',
      x: 500,
      y: 50,
      width: 100,
      height: 40,
      strokeColor: '#1e1e1e',
      backgroundColor: '#d0bfff',
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'text',
      x: 510,
      y: 60,
      width: 80,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      text: 'Database',
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 16,
      containerId: null,
      originalText: 'Database',
      lineHeight: 1.25,
      ...createBaseProps(),
    } as ExcalidrawElement,
    {
      id: generateId(),
      type: 'line',
      x: 550,
      y: 90,
      width: 0,
      height: 300,
      strokeColor: '#868e96',
      backgroundColor: 'transparent',
      strokeStyle: 'dashed',
      points: [[0, 0], [0, 300]],
      ...createBaseProps(),
    } as ExcalidrawElement,
  ],
};

// All templates
export const ALL_TEMPLATES: WhiteboardTemplate[] = [
  c4ContextTemplate,
  erdTemplate,
  sprintBoardTemplate,
  flowchartTemplate,
  userStoryMapTemplate,
  sequenceDiagramTemplate,
];

// Get templates by category
export function getTemplatesByCategory(
  category: WhiteboardTemplate['category']
): WhiteboardTemplate[] {
  return ALL_TEMPLATES.filter((t) => t.category === category);
}

// Get template by ID
export function getTemplateById(id: string): WhiteboardTemplate | undefined {
  return ALL_TEMPLATES.find((t) => t.id === id);
}

// Clone template elements with new IDs
export function cloneTemplateElements(
  template: WhiteboardTemplate,
  offsetX = 0,
  offsetY = 0
): ExcalidrawElement[] {
  const idMap = new Map<string, string>();

  return template.elements.map((el) => {
    const newId = generateId();
    idMap.set(el.id, newId);

    return {
      ...el,
      id: newId,
      x: el.x + offsetX,
      y: el.y + offsetY,
      seed: generateSeed(),
      versionNonce: generateSeed(),
      version: 1,
      updated: Date.now(),
    };
  });
}

export default ALL_TEMPLATES;
